# Jekyll LOCAL config for Design System
url: "http://localhost" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/scroll-line/_site" # the subpath of your site, e.g. /blog
#destination: ../marcelrent/public/proto-app # Build relative path destination. The destination directory e.g. /blog
# keep_files: [cache]
title: Style guide # title of the documentation
description: >- # Description of the docs. (>- means to ignore newlines until next param)
  UI and UX documentation for my app.

sidebar:
    logo:
        font_size: 32px # If no logo_url, font size of the site title 
        #url: https://www.example.com/logo.svg # Image URL: Can be local e.g. '/img/logo.png' or remote 'https://remotesite.com/img/logo.png'
        #max_height: 30px # Logo image max height
    additional_links:
        -   url: https://itautomotive-dev.github.io/bymycar-www/v1/
            title: Design System v1
            order: 1000
            category: Archives

playground:
    stylesheets: # Relative URL from site root, absolute URL with 'http'
        - styleguide/css/normalize.css
        - styleguide/css/prism.css
    #scripts_head: # Relative URL from site root, absolute URL with 'http'
    #    - https://test.com/jquery.min.js
    #    - script-head.js
    scripts_body: # Relative URL from site root, absolute URL with 'http'
        - https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js
        - styleguide/js/my-toggles.js

assets:
    path_from_root: / # The path from which files are available do download. '/' id the root
    extensions_enabled: # File extension to display
        - js
        - css
        - ttf
        - woff
        - woff2
        - otf
        - zip
        - sketch
        - svg
        - jpg
        - jpeg
        - gif
        - png
        - webp
        - psd
        - ai
    image_extensions: # Array list of image extensions (without point) to display as image into asset template
        - svg
        - jpg
        - jpeg
        - gif
        - png
        - webp
    



# Build settings - Do not edit excepting you do know what you do
#markdown: kramdown
kramdown:
    syntax_highlighter_opts:
        disable: true

sass:
    style: compressed
#exclude: ['/misc']

